import "~/styles/globals.css";

import { type Metadata } from "next";
import ReactQueryProvider from "~/components/providers/react-query";

export const metadata: Metadata = {
  title: "Echo Habit",
  description: "Generated by create-jaydee-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>{" "}
      </body>
    </html>
  );
}
