import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Echo Habit - Timer",
  description: "Generated by create-jaydee-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function TimerLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return <>{children}</>;
}
